name: Update Date
on:
  schedule:
    - cron: '0 0 * * *' # Ежедневно в 00:00 UTC
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README
        run: |
          // sed -i "s/Last update: .*/Last update: $(date '+%Y-%m-%d %H:%M')/g" README.md
          sed -i "s/Последнее обновление: .*/Последнее обновление: $(date -u '+%d.%m.%Y %H:%M MSK')/g" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update date"

          - name: Debug output
  run: |
    echo "Current date: $(date '+%Y-%m-%d %H:%M %Z')"
    cat README.md | grep "Последнее обновление"

    permissions:
  contents: write
  pull-requests: write
