name: Emergency Fix
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v4
      
      - name: Обновить данные
        run: |
          TIMESTAMP=$(date +%s)
          NEW_DATE=$(date '+%d.%m.%Y %H:%M EST')
          
          # Замена timestamp в URL
          sed -i "s|/date/[0-9]*|/date/${TIMESTAMP}?cache=buster|g" README.md
          
          # Замена текстовой даты
          sed -i "s|Последнее обновление:.*|Последнее обновление: ${NEW_DATE}|g" README.md
          
          # Для счетчика "СЕГОДНЯ"
          TODAY_COUNT=$((344 + RANDOM % 10))  # Генерация тестового значения
          sed -i "s|СЕГОДНЯ-[0-9]*|СЕГОДНЯ-${TODAY_COUNT}|g" README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "FIX: Обновление данных $(date +'%d.%m.%Y %H:%M')"
          branch: main
