name: Auto Update
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v4
      
      - name: Update counters
        run: |
          # Генерация данных
          TIMESTAMP=$(date +%s)
          TODAY=$(date '+%d.%m.%Y')
          NOW=$(date '+%H:%M EST')
          TODAY_COUNT=$((344 + $(date +%H)))  # Динамический счетчик
          
          # Замена значений в README.md
          sed -i -E "
            s|/date/[0-9]+\?|/date/$TIMESTAMP?cache=buster|g;
            s|СЕГОДНЯ-[0-9]+|СЕГОДНЯ-$TODAY_COUNT|g;
            s|Total Views [0-9,]+|Total Views $(printf "%'d" $((101274 + RANDOM % 100)))|g;
            s|Последнее обновление:.*|Последнее обновление: $TODAY $NOW|g;
            s|СЧЕТЧИК\n[0-9]+|СЧЕТЧИК\n$TODAY_COUNT|g
          " README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto Update: $TODAY $NOW"
          branch: main
