name: Auto Update Date Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

           - name: Get current UTC date
        run: echo "date=$(date -u +'%d.%m.%Y')" >> $GITHUB_ENV

      - name: Replace date in README
        run: |
          sed -i "s|{{date}}|${date}|g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "🕒 Автообновление даты: $DATE" || echo "No changes"
          git push
