name: Auto Update Date Badge

on:
  schedule:
    - cron: '0 0 * * *'  # каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current UTC date and replace in README
        run: |
          DATE=$(date -u +'%d.%m.%Y')
          echo "Текущая дата: $DATE"
          sed -i "s/{{DATE}}/${DATE}/g" README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git diff --quiet || (git commit -am "🕒 Обновление даты: $(date -u +'%d.%m.%Y')" && git push)
